#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GZ_SpotVisual.Resource", IsApplication=true)]

namespace GZ_SpotVisual
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int anim_slide_in_left = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int anim_slide_in_right = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int anim_slide_out_left = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int anim_slide_out_right = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int scale = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int translate = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int unscale = 2130968582;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int face = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int red = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int white = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060001
			public const int popup_name_text_size = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int popup_welcome_text_size = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int popupbg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int shape = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090008
			public const int alter = 2131296264;
			
			// aapt resource value: 0x7f090000
			public const int backTextView = 2131296256;
			
			// aapt resource value: 0x7f09000f
			public const int btnSave = 2131296271;
			
			// aapt resource value: 0x7f090009
			public const int faceImage = 2131296265;
			
			// aapt resource value: 0x7f09000c
			public const int include = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int koalaEditText = 2131296269;
			
			// aapt resource value: 0x7f090002
			public const int linearLayout1 = 2131296258;
			
			// aapt resource value: 0x7f090007
			public const int rl = 2131296263;
			
			// aapt resource value: 0x7f090003
			public const int settingTextView = 2131296259;
			
			// aapt resource value: 0x7f090001
			public const int textView1 = 2131296257;
			
			// aapt resource value: 0x7f090006
			public const int tvCopyright = 2131296262;
			
			// aapt resource value: 0x7f09000b
			public const int tvName = 2131296267;
			
			// aapt resource value: 0x7f090005
			public const int tvTime = 2131296261;
			
			// aapt resource value: 0x7f09000a
			public const int tvWecomeEmp = 2131296266;
			
			// aapt resource value: 0x7f090004
			public const int tvWelcome = 2131296260;
			
			// aapt resource value: 0x7f09000e
			public const int welcomeEditText1 = 2131296270;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int custom_title = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FaceMain = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Setting = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int visitor = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int ApplicationName = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080002
			public const int AppTheme = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int CustomTitleStyle = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int settingEditText = 2131230721;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
